framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    serializer:
        default_context:
            datetime_format: 'm.d.Y H:i'
            !php/const Symfony\Component\Serializer\Encoder\JsonEncode::OPTIONS: !php/const JSON_UNESCAPED_SLASHES

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
