security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        email:
            entity:
                class: App\Entity\User
                property: email
        app_provider:
            id: App\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api/tokens&
            lazy: true
            provider: app_provider
        api:
            pattern: ^/api/
            stateless: true
            provider: app_provider
            access_token:
                token_handler: App\Security\Authenticator\AccessTokenHandler
                token_extractors: App\Security\Authenticator\ApiKeyTokenExtractor
                failure_handler: App\Security\Authenticator\AuthenticationFailureHandler
    access_control:
        - { path: ^/api/tokens&, roles: PUBLIC_ACCESS, methods: ['POST'] }
        - { path: ^/api/presentations, roles: ROLE_USER, methods: ['GET', 'POST'] }
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: ['POST'] }
        - { path: ^/api/users, roles: ROLE_USER, methods: ['GET', 'PUT', 'DELETE'] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
