version: "3.8"

services:
  php:
    build:
      target: app_php
    networks:
      - polyclinic_network
    volumes:
      - ./:/var/www/api
    ports:
      - '9000:9000'

  nginx:
    image: nginx:alpine
    depends_on:
     - php
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/api
    networks:
      - polyclinic_network
    ports:
      - '80:80'

  database:
    image: mysql:8.0.32
    env_file:
      - docker/database/.env
    networks:
      - polyclinic_network
    volumes:
      - polyclinic_dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  polyclinic_network:
    driver: bridge

volumes:
  polyclinic_dbdata:
    name: 'polyclinic_dbdata'
